# ETL Transformation to create clean and targeted datasets for further analysis

In [1]:
#importing Dependancies
#============================================================================================
import pandas as pd
import matplotlib as mp
import numpy as np
from pathlib import Path

In [2]:
#loading data for transformation
#============================================================================================

file_path = Path('raw_data/nfl_pass_rush_receive_raw_data.csv')
df = pd.read_csv(file_path)

In [3]:
df.info

<bound method DataFrame.info of             game_id player_id pos                    player team  pass_cmp  \
0      201909050chi  RodgAa00  QB             Aaron Rodgers  GNB        18
1      201909050chi  JoneAa00  RB               Aaron Jones  GNB         0
2      201909050chi  ValdMa00  WR  Marquez Valdes-Scantling  GNB         0
3      201909050chi  AdamDa01  WR             Davante Adams  GNB         0
4      201909050chi  GrahJi00  TE              Jimmy Graham  GNB         0
...             ...       ...  ..                       ...  ...       ...
24339  202211280clt  TaylJo02  RB           Jonathan Taylor  IND         0
24340  202211280clt  HeywCo00  TE            Connor Heyward  PIT         0
24341  202211280clt  DuliAs00  WR              Ashton Dulin  IND         0
24342  202211280clt  KaliNi00  TE            Nikola Kalinic  IND         0
24343  202211280clt  JackDe02  RB              Deon Jackson  IND         0

       pass_att  pass_yds  pass_td  pass_int  ...     OT  \
0            30       203        1         0  ...  False
1             0         0        0         0  ...  False
2             0         0        0         0  ...  False
3             0         0        0         0  ...  False
4             0         0        0         0  ...  False
...         ...       ...      ...       ...  ...    ...
24339         0         0        0         0  ...  False
24340         0         0        0         0  ...  False
24341         0         0        0         0  ...  False
24342         0         0        0         0  ...  False
24343         0         0        0         0  ...  False

                            Roof     Surface  Temperature  Humidity  \
0                       outdoors       grass           65        69
1                       outdoors       grass           65        69
2                       outdoors       grass           65        69
3                       outdoors       grass           65        69
4                       outdoors       grass           65        69
...                          ...         ...          ...       ...
24339  retractable roof (closed)  fieldturf            72        45
24340  retractable roof (closed)  fieldturf            72        45
24341  retractable roof (closed)  fieldturf            72        45
24342  retractable roof (closed)  fieldturf            72        45
24343  retractable roof (closed)  fieldturf            72        45

       Wind_Speed  Vegas_Line  Vegas_Favorite  Over_Under   game_date
0              10        -3.5             CHI        47.0  2019-09-05
1              10        -3.5             CHI        47.0  2019-09-05
2              10        -3.5             CHI        47.0  2019-09-05
3              10        -3.5             CHI        47.0  2019-09-05
4              10        -3.5             CHI        47.0  2019-09-05
...           ...         ...             ...         ...         ...
24339           0         NaN             NaN         NaN  2022-11-28
24340           0         NaN             NaN         NaN  2022-11-28
24341           0         NaN             NaN         NaN  2022-11-28
24342           0         NaN             NaN         NaN  2022-11-28
24343           0         NaN             NaN         NaN  2022-11-28

[24344 rows x 69 columns]>

In [4]:
#checking number of columns and column names
#============================================================================================
df.columns

Index(['game_id', 'player_id', 'pos', 'player', 'team', 'pass_cmp', 'pass_att',
       'pass_yds', 'pass_td', 'pass_int', 'pass_sacked', 'pass_sacked_yds',
       'pass_long', 'pass_rating', 'rush_att', 'rush_yds', 'rush_td',
       'rush_long', 'targets', 'rec', 'rec_yds', 'rec_td', 'rec_long',
       'fumbles_lost', 'rush_scrambles', 'designed_rush_att',
       'comb_pass_rush_play', 'comb_pass_play', 'comb_rush_play',
       'Team_abbrev', 'Opponent_abbrev', 'two_point_conv', 'total_ret_td',
       'offensive_fumble_recovery_td', 'pass_yds_bonus', 'rush_yds_bonus',
       'rec_yds_bonus', 'Total_DKP', 'Off_DKP', 'Total_FDP', 'Off_FDP',
       'Total_SDP', 'Off_SDP', 'pass_target_yds', 'pass_poor_throws',
       'pass_blitzed', 'pass_hurried', 'rush_yds_before_contact', 'rush_yac',
       'rush_broken_tackles', 'rec_air_yds', 'rec_yac', 'rec_drops', 'offense',
       'off_pct', 'vis_team', 'home_team', 'vis_score', 'home_score', 'OT',
       'Roof', 'Surface', 'Temperature', 'Humidity', 'Wind_Speed',
       'Vegas_Line', 'Vegas_Favorite', 'Over_Under', 'game_date'],
      dtype='object')

In [5]:
#checking data types of columns
#============================================================================================
df.dtypes

game_id            object
player_id          object
pos                object
player             object
team               object
                   ...
Wind_Speed          int64
Vegas_Line        float64
Vegas_Favorite     object
Over_Under        float64
game_date          object
Length: 69, dtype: object

In [6]:
#checking dataframe structure
df.head()

,game_id,player_id,pos,player,team,pass_cmp,pass_att,pass_yds,pass_td,pass_int,...,OT,Roof,Surface,Temperature,Humidity,Wind_Speed,Vegas_Line,Vegas_Favorite,Over_Under,game_date
0,201909050chi,RodgAa00,QB,Aaron Rodgers,GNB,18,30,203,1,0,...,False,outdoors,grass,65,69,10,-3.5,CHI,47.0,2019-09-05
1,201909050chi,JoneAa00,RB,Aaron Jones,GNB,0,0,0,0,0,...,False,outdoors,grass,65,69,10,-3.5,CHI,47.0,2019-09-05
2,201909050chi,ValdMa00,WR,Marquez Valdes-Scantling,GNB,0,0,0,0,0,...,False,outdoors,grass,65,69,10,-3.5,CHI,47.0,2019-09-05
3,201909050chi,AdamDa01,WR,Davante Adams,GNB,0,0,0,0,0,...,False,outdoors,grass,65,69,10,-3.5,CHI,47.0,2019-09-05
4,201909050chi,GrahJi00,TE,Jimmy Graham,GNB,0,0,0,0,0,...,False,outdoors,grass,65,69,10,-3.5,CHI,47.0,2019-09-05

In [7]:
#count number of null values in data frame so we can drop unnecessary rows
df.isna().sum().sum()

4222

In [8]:
#declaring new data frame with no NA values 
df2 = df.dropna()

In [9]:
#verifying NAN was dropoed
len(df2.index)

22906

In [10]:
#creating dataframe with all passing data 
#======================================================================================
passing_data_raw = df2.loc[df2['pass_att']>0]

passing_data_raw

,game_id,player_id,pos,player,team,pass_cmp,pass_att,pass_yds,pass_td,pass_int,...,OT,Roof,Surface,Temperature,Humidity,Wind_Speed,Vegas_Line,Vegas_Favorite,Over_Under,game_date
0,201909050chi,RodgAa00,QB,Aaron Rodgers,GNB,18,30,203,1,0,...,False,outdoors,grass,65,69,10,-3.5,CHI,47.0,2019-09-05
9,201909050chi,TrubMi00,QB,Mitchell Trubisky,CHI,26,45,228,0,1,...,False,outdoors,grass,65,69,10,-3.5,CHI,47.0,2019-09-05
29,201909080car,GoffJa00,QB,Jared Goff,LAR,23,39,186,1,1,...,False,outdoors,grass,87,53,3,-1.5,LAR,49.5,2019-09-08
36,201909080car,NewtCa00,QB,Cam Newton,CAR,25,38,239,0,1,...,False,outdoors,grass,87,53,3,-1.5,LAR,49.5,2019-09-08
44,201909080cle,MariMa01,QB,Marcus Mariota,TEN,14,24,248,3,0,...,False,outdoors,grass,71,55,10,-5.5,CLE,44.0,2019-09-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22904,202210300sea,JoneDa05,QB,Daniel Jones,NYG,17,31,176,0,0,...,False,outdoors,fieldturf,54,83,8,-3.0,SEA,44.5,2022-10-30
22910,202210300sea,SmitGe00,QB,Geno Smith,SEA,23,34,212,2,0,...,False,outdoors,fieldturf,54,83,8,-3.0,SEA,44.5,2022-10-30
22940,202210310cle,BrisJa00,QB,Jacoby Brissett,CLE,17,22,278,1,0,...,False,outdoors,grass,66,68,9,-3.0,CIN,45.0,2022-10-31
22941,202210310cle,CoopAm00,WR,Amari Cooper,CLE,0,1,0,0,1,...,False,outdoors,grass,66,68,9,-3.0,CIN,45.0,2022-10-31
22943,202210310cle,BurrJo01,QB,Joe Burrow,CIN,25,35,232,2,1,...,False,outdoors,grass,66,68,9,-3.0,CIN,45.0,2022-10-31

In [11]:
#dropping unnecessary columns for more valuable insight
#=====================================================================================================================
passing_data_df = passing_data_raw[['game_id', 'player_id','pos','player','team','pass_cmp','pass_att','pass_yds','pass_td','pass_int','pass_sacked','pass_sacked_yds','pass_long','pass_rating','fumbles_lost']]
passing_data_df

,game_id,player_id,pos,player,team,pass_cmp,pass_att,pass_yds,pass_td,pass_int,pass_sacked,pass_sacked_yds,pass_long,pass_rating,fumbles_lost
0,201909050chi,RodgAa00,QB,Aaron Rodgers,GNB,18,30,203,1,0,5,37,47,91.4,0
9,201909050chi,TrubMi00,QB,Mitchell Trubisky,CHI,26,45,228,0,1,5,20,27,62.1,0
29,201909080car,GoffJa00,QB,Jared Goff,LAR,23,39,186,1,1,1,3,24,69.0,0
36,201909080car,NewtCa00,QB,Cam Newton,CAR,25,38,239,0,1,3,23,17,72.1,1
44,201909080cle,MariMa01,QB,Marcus Mariota,TEN,14,24,248,3,0,4,32,75,133.3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22904,202210300sea,JoneDa05,QB,Daniel Jones,NYG,17,31,176,0,0,5,29,27,71.4,0
22910,202210300sea,SmitGe00,QB,Geno Smith,SEA,23,34,212,2,0,3,22,33,104.0,0
22940,202210310cle,BrisJa00,QB,Jacoby Brissett,CLE,17,22,278,1,0,2,10,53,133.7,1
22941,202210310cle,CoopAm00,WR,Amari Cooper,CLE,0,1,0,0,1,0,0,0,0.0,0
22943,202210310cle,BurrJo01,QB,Joe Burrow,CIN,25,35,232,2,1,5,39,41,96.4,1

In [12]:
#grouping dataframe by each unique player name for later analysis
#===========================================================================================================================
new_passing_data_df = passing_data_df.groupby('player')
new_passing_data_df.head()

,game_id,player_id,pos,player,team,pass_cmp,pass_att,pass_yds,pass_td,pass_int,pass_sacked,pass_sacked_yds,pass_long,pass_rating,fumbles_lost
0,201909050chi,RodgAa00,QB,Aaron Rodgers,GNB,18,30,203,1,0,5,37,47,91.4,0
9,201909050chi,TrubMi00,QB,Mitchell Trubisky,CHI,26,45,228,0,1,5,20,27,62.1,0
29,201909080car,GoffJa00,QB,Jared Goff,LAR,23,39,186,1,1,1,3,24,69.0,0
36,201909080car,NewtCa00,QB,Cam Newton,CAR,25,38,239,0,1,3,23,17,72.1,1
44,201909080cle,MariMa01,QB,Marcus Mariota,TEN,14,24,248,3,0,4,32,75,133.3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22860,202210300phi,PickKe00,QB,Kenny Pickett,PIT,25,38,191,0,1,6,38,25,66.9,1
22861,202210300phi,HarrNa00,RB,Najee Harris,PIT,1,1,4,0,0,0,0,4,83.3,0
22862,202210300phi,ClayCh01,WR,Chase Claypool,PIT,1,1,1,1,0,0,0,1,118.7,0
22887,202210300ram,McCaCh01,RB,Christian McCaffrey,SFO,1,1,34,1,0,0,0,34,158.3,0
22941,202210310cle,CoopAm00,WR,Amari Cooper,CLE,0,1,0,0,1,0,0,0,0.0,0

In [13]:
#totaling all recorded passing statistics after the previous block grouped by player name. We are resetting index in new dataframe. 
cleaned_passing_data = new_passing_data_df.sum()
cleaned_passing_data =cleaned_passing_data.reset_index()
cleaned_passing_data

,player,pass_cmp,pass_att,pass_yds,pass_td,pass_int,pass_sacked,pass_sacked_yds,pass_long,pass_rating,fumbles_lost
0,A.J. Brown,0,2,0,0,0,0,0,0,79.2,0
1,A.J. McCarron,22,38,245,0,1,5,43,41,223.5,0
2,Aaron Rodgers,1396,2079,15652,133,20,118,887,2608,6524.6,10
3,Albert Wilson,1,3,20,0,0,0,0,20,125.0,0
4,Alex Erickson,1,2,26,0,0,0,0,26,158.3,0
...,...,...,...,...,...,...,...,...,...,...,...
203,Tyrod Taylor,112,189,1218,6,6,15,120,260,766.6,0
204,Will Grier,28,52,228,0,4,6,44,32,46.0,1
205,Zach Pascal,0,2,0,0,0,0,0,0,79.2,0
206,Zach Wilson,291,525,3382,12,16,54,443,661,1293.6,1
207,Zay Jones,1,1,29,0,0,0,0,29,118.7,0

In [29]:
cleaned_passing_data['pass_rating'] =cleaned_passing_data['pass_rating']/new_passing_data_df['player'].value_count()

AttributeError: 'SeriesGroupBy' object has no attribute 'value_count'

In [14]:
#displaying column names 
#================================================================
df2.columns

Index(['game_id', 'player_id', 'pos', 'player', 'team', 'pass_cmp', 'pass_att',
       'pass_yds', 'pass_td', 'pass_int', 'pass_sacked', 'pass_sacked_yds',
       'pass_long', 'pass_rating', 'rush_att', 'rush_yds', 'rush_td',
       'rush_long', 'targets', 'rec', 'rec_yds', 'rec_td', 'rec_long',
       'fumbles_lost', 'rush_scrambles', 'designed_rush_att',
       'comb_pass_rush_play', 'comb_pass_play', 'comb_rush_play',
       'Team_abbrev', 'Opponent_abbrev', 'two_point_conv', 'total_ret_td',
       'offensive_fumble_recovery_td', 'pass_yds_bonus', 'rush_yds_bonus',
       'rec_yds_bonus', 'Total_DKP', 'Off_DKP', 'Total_FDP', 'Off_FDP',
       'Total_SDP', 'Off_SDP', 'pass_target_yds', 'pass_poor_throws',
       'pass_blitzed', 'pass_hurried', 'rush_yds_before_contact', 'rush_yac',
       'rush_broken_tackles', 'rec_air_yds', 'rec_yac', 'rec_drops', 'offense',
       'off_pct', 'vis_team', 'home_team', 'vis_score', 'home_score', 'OT',
       'Roof', 'Surface', 'Temperature', 'Humidity', 'Wind_Speed',
       'Vegas_Line', 'Vegas_Favorite', 'Over_Under', 'game_date'],
      dtype='object')

In [15]:
#creating dataframe with all rushing data 
#======================================================================================
rushing_data_df_raw = df2.loc[df2['rush_att']>0]
rushing_data_df_raw.head()

,game_id,player_id,pos,player,team,pass_cmp,pass_att,pass_yds,pass_td,pass_int,...,OT,Roof,Surface,Temperature,Humidity,Wind_Speed,Vegas_Line,Vegas_Favorite,Over_Under,game_date
0,201909050chi,RodgAa00,QB,Aaron Rodgers,GNB,18,30,203,1,0,...,False,outdoors,grass,65,69,10,-3.5,CHI,47.0,2019-09-05
1,201909050chi,JoneAa00,RB,Aaron Jones,GNB,0,0,0,0,0,...,False,outdoors,grass,65,69,10,-3.5,CHI,47.0,2019-09-05
2,201909050chi,ValdMa00,WR,Marquez Valdes-Scantling,GNB,0,0,0,0,0,...,False,outdoors,grass,65,69,10,-3.5,CHI,47.0,2019-09-05
7,201909050chi,WillJa06,RB,Jamaal Williams,GNB,0,0,0,0,0,...,False,outdoors,grass,65,69,10,-3.5,CHI,47.0,2019-09-05
9,201909050chi,TrubMi00,QB,Mitchell Trubisky,CHI,26,45,228,0,1,...,False,outdoors,grass,65,69,10,-3.5,CHI,47.0,2019-09-05

In [16]:
#creating datafrome with columns relevant to rushing statistics
#select appropriate columns below 
#======================================================================================
rushing_data_df = rushing_data_df_raw[['game_id', 'player_id','pos','player','team','rush_att','rush_yds','rush_td','rush_long','fumbles_lost','rush_scrambles','designed_rush_att','rush_yds_before_contact','rush_broken_tackles']]
rushing_data_df

,game_id,player_id,pos,player,team,rush_att,rush_yds,rush_td,rush_long,fumbles_lost,rush_scrambles,designed_rush_att,rush_yds_before_contact,rush_broken_tackles
0,201909050chi,RodgAa00,QB,Aaron Rodgers,GNB,3,8,0,10,0,1,2,6,0
1,201909050chi,JoneAa00,RB,Aaron Jones,GNB,13,39,0,9,0,0,13,21,1
2,201909050chi,ValdMa00,WR,Marquez Valdes-Scantling,GNB,1,0,0,0,0,0,1,0,0
7,201909050chi,WillJa06,RB,Jamaal Williams,GNB,5,0,0,5,0,0,5,0,0
9,201909050chi,TrubMi00,QB,Mitchell Trubisky,CHI,3,11,0,7,0,2,1,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22940,202210310cle,BrisJa00,QB,Jacoby Brissett,CLE,6,12,1,4,1,1,5,0,0
22942,202210310cle,ChubNi00,RB,Nick Chubb,CLE,23,101,2,21,0,0,23,59,4
22943,202210310cle,BurrJo01,QB,Joe Burrow,CIN,1,2,0,2,1,0,1,0,0
22944,202210310cle,MixoJo00,RB,Joe Mixon,CIN,8,27,0,6,0,0,8,11,0
22945,202210310cle,PeriSa00,RB,Samaje Perine,CIN,1,7,0,7,0,0,1,2,0

In [17]:
#grouping dataframe by each unique player name for later analysis
#===========================================================================================================================
new_rushing_data_df = rushing_data_df.groupby('player')
new_rushing_data_df.head()

,game_id,player_id,pos,player,team,rush_att,rush_yds,rush_td,rush_long,fumbles_lost,rush_scrambles,designed_rush_att,rush_yds_before_contact,rush_broken_tackles
0,201909050chi,RodgAa00,QB,Aaron Rodgers,GNB,3,8,0,10,0,1,2,6,0
1,201909050chi,JoneAa00,RB,Aaron Jones,GNB,13,39,0,9,0,0,13,21,1
2,201909050chi,ValdMa00,WR,Marquez Valdes-Scantling,GNB,1,0,0,0,0,0,1,0,0
7,201909050chi,WillJa06,RB,Jamaal Williams,GNB,5,0,0,5,0,0,5,0,0
9,201909050chi,TrubMi00,QB,Mitchell Trubisky,CHI,3,11,0,7,0,2,1,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22812,202210300nor,AdamDa01,WR,Davante Adams,LVR,1,-1,0,-1,0,0,1,-1,0
22813,202210300nor,FarlMa00,FS,Matthias Farley,LVR,1,-3,0,-3,0,0,1,-3,0
22860,202210300phi,PickKe00,QB,Kenny Pickett,PIT,7,37,0,11,1,5,2,36,0
22865,202210300phi,AlleMa03,LB,Marcus Allen,PIT,1,4,0,4,0,0,1,4,0
22893,202210300ram,RiveRo01,RB,Ronnie Rivers,LAR,8,21,0,5,0,0,8,16,0

In [18]:
#totaling all recorded passing statistics after the previous block grouped by player name. We are resetting index in new dataframe.
cleaned_rushing_data = new_rushing_data_df.sum()
cleaned_rushing_data =cleaned_rushing_data.reset_index()
cleaned_rushing_data

,player,rush_att,rush_yds,rush_td,rush_long,fumbles_lost,rush_scrambles,designed_rush_att,rush_yds_before_contact,rush_broken_tackles
0,A.J. Brown,6,79,1,79,0,0,6,18,2
1,A.J. McCarron,5,39,1,18,0,5,0,39,0
2,AJ Cole III,1,0,0,0,0,0,1,0,0
3,AJ Dillon,336,1469,9,441,1,0,336,757,26
4,Aaron Jones,771,3847,34,1207,5,0,771,1944,70
...,...,...,...,...,...,...,...,...,...,...
639,Zach Zenner,3,-2,0,-2,0,0,3,-2,0
640,Zack Moss,233,938,8,380,2,0,233,428,27
641,Zamir White,5,21,0,19,0,0,5,9,0
642,Zander Horvath,3,5,0,5,0,0,3,3,0
643,Zay Jones,6,27,0,27,0,0,6,25,0

In [19]:
#creating dataframe with all receiving data 
#======================================================================================
receiving_data_raw = df2.loc[df2['targets']>0]
receiving_data_raw

,game_id,player_id,pos,player,team,pass_cmp,pass_att,pass_yds,pass_td,pass_int,...,OT,Roof,Surface,Temperature,Humidity,Wind_Speed,Vegas_Line,Vegas_Favorite,Over_Under,game_date
1,201909050chi,JoneAa00,RB,Aaron Jones,GNB,0,0,0,0,0,...,False,outdoors,grass,65,69,10,-3.5,CHI,47.0,2019-09-05
2,201909050chi,ValdMa00,WR,Marquez Valdes-Scantling,GNB,0,0,0,0,0,...,False,outdoors,grass,65,69,10,-3.5,CHI,47.0,2019-09-05
3,201909050chi,AdamDa01,WR,Davante Adams,GNB,0,0,0,0,0,...,False,outdoors,grass,65,69,10,-3.5,CHI,47.0,2019-09-05
4,201909050chi,GrahJi00,TE,Jimmy Graham,GNB,0,0,0,0,0,...,False,outdoors,grass,65,69,10,-3.5,CHI,47.0,2019-09-05
5,201909050chi,DaviTr03,WR,Trevor Davis,GNB,0,0,0,0,0,...,False,outdoors,grass,65,69,10,-3.5,CHI,47.0,2019-09-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22942,202210310cle,ChubNi00,RB,Nick Chubb,CLE,0,0,0,0,0,...,False,outdoors,grass,66,68,9,-3.0,CIN,45.0,2022-10-31
22944,202210310cle,MixoJo00,RB,Joe Mixon,CIN,0,0,0,0,0,...,False,outdoors,grass,66,68,9,-3.0,CIN,45.0,2022-10-31
22945,202210310cle,PeriSa00,RB,Samaje Perine,CIN,0,0,0,0,0,...,False,outdoors,grass,66,68,9,-3.0,CIN,45.0,2022-10-31
22946,202210310cle,HiggTe00,WR,Tee Higgins,CIN,0,0,0,0,0,...,False,outdoors,grass,66,68,9,-3.0,CIN,45.0,2022-10-31
22947,202210310cle,HursHa00,TE,Hayden Hurst,CIN,0,0,0,0,0,...,False,outdoors,grass,66,68,9,-3.0,CIN,45.0,2022-10-31

In [20]:
#displaying column names 
#================================================================
df2.columns

Index(['game_id', 'player_id', 'pos', 'player', 'team', 'pass_cmp', 'pass_att',
       'pass_yds', 'pass_td', 'pass_int', 'pass_sacked', 'pass_sacked_yds',
       'pass_long', 'pass_rating', 'rush_att', 'rush_yds', 'rush_td',
       'rush_long', 'targets', 'rec', 'rec_yds', 'rec_td', 'rec_long',
       'fumbles_lost', 'rush_scrambles', 'designed_rush_att',
       'comb_pass_rush_play', 'comb_pass_play', 'comb_rush_play',
       'Team_abbrev', 'Opponent_abbrev', 'two_point_conv', 'total_ret_td',
       'offensive_fumble_recovery_td', 'pass_yds_bonus', 'rush_yds_bonus',
       'rec_yds_bonus', 'Total_DKP', 'Off_DKP', 'Total_FDP', 'Off_FDP',
       'Total_SDP', 'Off_SDP', 'pass_target_yds', 'pass_poor_throws',
       'pass_blitzed', 'pass_hurried', 'rush_yds_before_contact', 'rush_yac',
       'rush_broken_tackles', 'rec_air_yds', 'rec_yac', 'rec_drops', 'offense',
       'off_pct', 'vis_team', 'home_team', 'vis_score', 'home_score', 'OT',
       'Roof', 'Surface', 'Temperature', 'Humidity', 'Wind_Speed',
       'Vegas_Line', 'Vegas_Favorite', 'Over_Under', 'game_date'],
      dtype='object')

In [21]:
#creating datafrome with columns relevant to rushing statistics
#select appropriate columns below 
#======================================================================================
receiving_data_df = receiving_data_raw[['game_id', 'player_id','pos','player','team','targets','rec','rec_yds','rec_td','rec_long','rec_air_yds','rec_yac','rec_drops']]
receiving_data_df

,game_id,player_id,pos,player,team,targets,rec,rec_yds,rec_td,rec_long,rec_air_yds,rec_yac,rec_drops
1,201909050chi,JoneAa00,RB,Aaron Jones,GNB,1,1,0,0,0,-1.0,1,0
2,201909050chi,ValdMa00,WR,Marquez Valdes-Scantling,GNB,6,4,52,0,47,81.0,2,0
3,201909050chi,AdamDa01,WR,Davante Adams,GNB,8,4,36,0,11,63.2,19,0
4,201909050chi,GrahJi00,TE,Jimmy Graham,GNB,5,3,30,1,16,58.0,17,0
5,201909050chi,DaviTr03,WR,Trevor Davis,GNB,1,1,28,0,28,18.0,10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22942,202210310cle,ChubNi00,RB,Nick Chubb,CLE,1,1,3,0,3,-7.0,10,0
22944,202210310cle,MixoJo00,RB,Joe Mixon,CIN,9,7,32,0,14,-20.7,48,1
22945,202210310cle,PeriSa00,RB,Samaje Perine,CIN,3,3,10,0,6,-8.1,18,0
22946,202210310cle,HiggTe00,WR,Tee Higgins,CIN,6,3,49,1,41,87.0,11,0
22947,202210310cle,HursHa00,TE,Hayden Hurst,CIN,4,4,42,0,21,29.2,13,0

In [22]:
#grouping dataframe by each unique player name for later analysis
#===========================================================================================================================
new_receiving_data_df = receiving_data_df.groupby('player')
new_receiving_data_df.head()

,game_id,player_id,pos,player,team,targets,rec,rec_yds,rec_td,rec_long,rec_air_yds,rec_yac,rec_drops
1,201909050chi,JoneAa00,RB,Aaron Jones,GNB,1,1,0,0,0,-1.0,1,0
2,201909050chi,ValdMa00,WR,Marquez Valdes-Scantling,GNB,6,4,52,0,47,81.0,2,0
3,201909050chi,AdamDa01,WR,Davante Adams,GNB,8,4,36,0,11,63.2,19,0
4,201909050chi,GrahJi00,TE,Jimmy Graham,GNB,5,3,30,1,16,58.0,17,0
5,201909050chi,DaviTr03,WR,Trevor Davis,GNB,1,1,28,0,28,18.0,10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22909,202210300sea,CageLa01,TE,Lawrence Cager,NYG,1,0,0,0,0,22.0,0,0
22911,202210300sea,WalkKe00,RB,Kenneth Walker III,SEA,2,1,1,0,1,6.0,0,0
22918,202210300sea,RobiWa01,WR,Wan'Dale Robinson,NYG,3,2,15,0,9,12.0,7,0
22934,202210310cle,WoodMi00,WR,Michael Woods II,CLE,2,1,6,0,6,21.0,3,0
22935,202210310cle,IrwiTr00,WR,Trenton Irwin,CIN,3,2,27,0,18,18.9,6,0

In [23]:
#totaling all recorded passing statistics after the previous block grouped by player name. We are resetting index in new dataframe.
cleaned_receiving_data = new_receiving_data_df.sum()
cleaned_receiving_data =cleaned_receiving_data.reset_index()
cleaned_receiving_data

,player,targets,rec,rec_yds,rec_td,rec_long,rec_air_yds,rec_yac,rec_drops
0,A.J. Brown,387,240,3943,31,1639,4573.1,1462,21
1,A.J. Green,222,111,1427,5,662,2864.9,279,10
2,AJ Dillon,61,51,436,2,276,28.5,418,4
3,Aaron Brewer,1,0,0,0,0,3.0,0,0
4,Aaron Jones,259,198,1591,15,790,309.6,1583,14
...,...,...,...,...,...,...,...,...,...
877,Zach Zenner,3,2,19,0,19,5.0,19,1
878,Zack Moss,62,48,345,2,201,60.8,334,3
879,Zander Horvath,7,4,7,2,6,5.0,1,1
880,Zay Jones,185,121,1236,4,684,1998.9,415,7
881,Zeke Turner,1,1,26,0,26,14.0,12,0

In [24]:
#exporting each dataframe as csv for further analysis and storage
cleaned_receiving_data.to_csv('cleaned_data/receiving_data.csv')
cleaned_rushing_data.to_csv('cleaned_data/rushing_data.csv')
cleaned_passing_data.to_csv('cleaned_data/passing_data.csv')

In [25]:
#verifying there are no null values in the dataframe 
#====================================================
cleaned_passing_data.isna().sum().sum()

0

In [26]:
#verifying there are no null values in the dataframe 
#====================================================
cleaned_rushing_data.isna().sum().sum()

0

In [27]:
#verifying there are no null values in the dataframe 
#====================================================
cleaned_receiving_data.isna().sum().sum()

0